name:                ledger-sak
version:             0.1.0.0
github:              "gregorias/ledger-sak"
license:             AGPL-3
author:              "Grzegorz Milka"
maintainer:          "grzegorzmilka@gmail.com"
copyright:           "Copyright (c) 2021 Grzegorz Milka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregorias/ledger-sak#readme>

# Defaults recommended by https://kowainik.github.io/posts/2019-02-06-style-guide#default-extensions
# Also use Relude
default-extensions:
  DerivingStrategies
  GeneralisedNewtypeDeriving
  InstanceSigs
  LambdaCase
  MultiWayIf
  NoImplicitPrelude
  NumericUnderscores
  ScopedTypeVariables
  TupleSections
  TypeApplications
  UnicodeSyntax
  QuasiQuotes
  OverloadedLists
  OverloadedStrings

dependencies:
- base >= 4.13 && < 5
- relude

library:
  source-dirs: src
  ghc-options:
  - -Wunused-packages
  dependencies:
  - containers
  - Diff
  - megaparsec
  - text
  - time

executables:
  ledgerdiff:
    main:                LedgerDiffMain.hs
    source-dirs:         ledgerdiff
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is LedgerDiffMain
    - -Wunused-packages
    dependencies:
    - ledger-sak
    - optparse-applicative

tests:
  ledger-sak-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Spec
    - -Wunused-packages
    dependencies:
    - hspec
    - hspec-expectations-pretty-diff
    - ledger-sak
    - neat-interpolation
    - time

  doctest:
    main:                DocTest.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DocTest
    dependencies:
    - doctest
    - ledger-sak
